# Site settings
title: Shattered ThoughtsðŸ§ 
SEOTitle: Cattouch's Shattered ThoughtsðŸ§ 
header-img: img/post-bg-desk.jpg
email: cattouch@protonmail.com
description: "A desire to explore the unknown world."
keyword: "World,United State,Jpan,China"
url: "http://cattouch.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/cattouch/cattouch.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
#twitter_username:     creating
github_username:    cattouch
#facebook_username:  creating
#quora_username:   creating
#reddit_username:   creating




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 
# Disqusï¼ˆhttps://disqus.com/ï¼‰
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false
  clientID: f2c84e7629bb1446c1a4                            
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    
  repo: cattouch.github.io    
  owner: cattouch    
  admin: cattouch
  distractionFreeMode: true


# ç»Ÿè®¡

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'           
ga_domain: auto





# Featured Tags
featured-tags: true                    
featured-condition-size: 1             



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
   {
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
